branches:
  only:
  - master
language: r
os: osx
cache: packages
fortran: false
r:
# - 3.2
# - 3.3
# - 3.4
- 3.5
- release
# CRAN doesn't host macOS binary packages for r-devel
# - devel
env:
  LOCAL_AUTOBREW: "TRUE"
  TEST_R_WITH_ARROW: "TRUE"
before_install:
- git clone --depth=1 https://github.com/apache/arrow.git
- cd arrow/r
- git log -n 1 # To show what commit is being built
# This script used to be inside r/tools/ but was moved
- cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
- source ../../up-date-description.sh
script:
# Use a custom "script" to add travis_wait in order to prevent build timeouts
- travis_wait R CMD build --no-build-vignettes .
# Don't run --as-cran because CRAN doesn't on macOS (also autobrew chokes on R 3.6.2)
# See https://issues.apache.org/jira/browse/ARROW-7416
- travis_wait R CMD check arrow_*.tar.gz --no-manual --ignore-vignettes --install-args="--build"
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && travis_wait Rscript -e 'install.packages("covr"); covr::codecov()'
- source ../../bintray-upload.sh
- cat /Users/travis/build/ursa-labs/arrow-r-nightly/arrow/r/arrow.Rcheck/00install.out
after_failure:
- cat /Users/travis/build/ursa-labs/arrow-r-nightly/arrow/r/arrow.Rcheck/00install.out
