name: Build binary C++ libraries

on:
  schedule:
    - cron: |
        0 12 * * *
  push:
    paths:
      - '.github/workflows/build-binary.yml'
      - 'linux/*'
      - bintray-upload.sh
      - up-date-description.sh

jobs:
  binaries:
    name: C++ Binary ${{ matrix.config.os }}-${{ matrix.config.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu, version: '16.04'}
        - { os: ubuntu, version: '18.04'}
        - { os: debian, version: '9'}
        - { os: debian, version: '10'}
        - { os: centos, version: '7'}
        - { os: centos, version: '8'}
    env:
      VERSION: ${{ matrix.config.version }}
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Clone apache/arrow and checkout at date
        shell: bash
        run: |
          cd linux
          git clone https://github.com/nealrichardson/arrow
          cd arrow
          # Check out the release branch instead
          # git checkout `git rev-list -n 1 --before="00:00" master`
          git checkout 0.16.0.2-rpkg
      - name: Build
        shell: bash
        run: |
          cd linux
          docker-compose build ${{ matrix.config.os }}
          docker-compose run ${{ matrix.config.os }}
      - name: Bundle and upload
        env:
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
        shell: bash
        run: |
          cd linux/arrow/r
          # Don't update the dates because the version is right already
          # export DATE=$(date -d yesterday +%Y%m%d)
          # source ../../../up-date-description.sh
          VERSION=$(grep ^Version DESCRIPTION | sed s/Version:\ //)
          export PKG_FILE="arrow-${VERSION}.zip"
          cd libarrow/dist
          # These files were created by the docker user so we have to sudo to get them
          sudo -E zip -r $PKG_FILE lib/*.a include/
          export REPO_PATH=/libarrow/bin/${{ matrix.config.os }}-${{ matrix.config.version }}
          sudo -E bash ../../../../../bintray-upload.sh
