name: Source packages

on:
  schedule:
    - cron: |
        0 1 * * *
  push:
    paths:
      - ".github/workflows/build-source.yml"
      - s3-upload.py
      - bintray-upload.sh
      - up-date-description.sh

jobs:
  source:
    name: Source packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Clone apache/arrow
        shell: bash
        run: |
          git clone https://github.com/apache/arrow
      - name: Checkout arrow at date and update R package version
        shell: bash
        run: |
          cd arrow
          git checkout `git rev-list -n 1 --before="00:00" master`
          cd r
          export DATE=$(date -d yesterday +%Y%m%d)
          source ../../up-date-description.sh
      - name: Set up Python (for S3 upload)
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Boto
        run: |
          python -m pip install boto3
      - name: Build and upload cpp bundle
        env:
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
        run: |
          cd arrow
          VERSION=$(grep ^Version r/DESCRIPTION | sed s/Version:\ //)
          zip -r arrow-${VERSION}.zip cpp/build-support/ cpp/cmake_modules/ cpp/src/ cpp/thirdparty/ cpp/tools/ cpp/CMakeLists.txt cpp/README.md LICENSE.txt NOTICE.txt .env
          PKG_FILE=arrow-${VERSION}.zip REPO_PATH=/libarrow/src source ../bintray-upload.sh
          # Or to upload to S3:
          python ../s3-upload.py arrow-${VERSION}.zip libarrow/src
      - name: Install R
        uses: r-lib/actions/setup-r@master
      - name: Build and upload R source package
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
        run: |
          cd arrow/r
          cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
          # Pin the git commit in the formula to match
          cd tools
          sed -i.bak -E -e 's/arrow.git"$/arrow.git", :revision => "'"$(git rev-list -n 1 HEAD)"'"/' apache-arrow.rb
          rm -f apache-arrow.rb.bak
          # NOTE: if you want to change the source of the libarrow files away
          # from bintray, sed linuxlibs.R and winlibs.R
          cd ..
          R CMD build --no-build-vignettes .
          Rscript -e 'tools::write_PACKAGES(".", type = "source")'
          python ../../s3-upload.py arrow_*.tar.gz src/contrib
          python ../../s3-upload.py PACKAGES src/contrib
          python ../../s3-upload.py PACKAGES.gz src/contrib
          python ../../s3-upload.py PACKAGES.rds src/contrib
