name: Test installation from Bintray

on:
  schedule:
    - cron: |
        0 */23 * * *
  push:
    paths:
      - '.github/workflows/test-install.yml'
      - 'linux/*'
  # On tag too?

jobs:
  source:
    name: Source packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Install R
        uses: r-lib/actions/setup-r@master
      - name: Install arrow from binatray
        env:
          # Test source build so be sure not to download a binary
          LIBARROW_BINARY_DISTRO: "FALSE"
        run: Rscript linux/install-arrow.R
  binary:
    name: Binary packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "rhub/ubuntu-gcc-release"
          - "rstudio/r-base:3.6-bionic"
          - "rstudio/r-base:3.6-centos7"
          - "rstudio/r-base:3.6-centos8"
          - "rocker/r-ver" # for debian:stretch (9)
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Install arrow from binatray
        env:
          DOCKER_IMAGE: ${{ matrix.image }}
        run: |
          set -ex
          cd linux
          docker run -v $(pwd):/linux $DOCKER_IMAGE \
            -e LIBARROW_BUILD=FALSE \
            /bin/bash -c "Rscript linux/install-arrow.R"
