name: Test binary installation

on:
  schedule:
    - cron: |
        0 23 * * *
  push:
    paths:
      - '.github/workflows/test-binary.yml'
      - 'linux/install-arrow.R'
      - 'linux/distro-map.csv'
  # On tag too?

jobs:
  binary:
    name: Binary packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - "rhub/ubuntu-gcc-release" # ubuntu-16.04
          - "rstudio/r-base:3.6-bionic"
          - "rstudio/r-base:3.6-centos7"
          - "rstudio/r-base:3.6-centos8"
          - "rocker/r-ver" # for debian:stretch (9)
          - "rhub/fedora-clang-devel" # tests distro-map.csv, mapped to centos-8
    steps:
      - name: Checkout arrow-r-nightly
        uses: actions/checkout@v1
      - name: Install arrow from binatray
        env:
          DOCKER_IMAGE: ${{ matrix.image }}
        run: |
          set -ex
          cd linux
          docker run \
            -e LIBARROW_BUILD=FALSE \
            -e LIBARROW_DOWNLOAD=TRUE \
            -v $(pwd):/linux \
            $DOCKER_IMAGE \
            /bin/bash -c "PATH=/opt/R-devel/bin:$PATH Rscript linux/install-arrow.R"
